[build-system]
requires = ["uv_build>=0.8.9,<0.9.0"]
build-backend = "uv_build"

[project]
name = "tsod"
version = "0.3.0"
description = "Time series anomaly detection."
authors = [
    { name = "Henrik Andersson", email = "jan@dhigroup.com" },
    { name = "Lars Jonasson", email = "lajo@dhigroup.com" },
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["pandas>=2.0.0", "joblib", "numba", "typing_extensions"]

classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
]

[dependency-groups]
test = ["pytest>=6", "pytest-cov>=4"]

dev = [
    { include-group = "test" },
    { include-group = "docs" },
    "ruff==0.14.5",
    "pandas-stubs",
]

docs = [
    "nbclient>=0.10.2",
    "nbformat>=5.10.4",
    "quarto-cli>=1.8.25",
    "quartodoc>=0.11.1",
    "griffe<2",
]

[project.urls]
"Homepage" = "https://github.com/DHI/tsod"
"Bug Tracker" = "https://github.com/DHI/tsod/issues"


[tool.ruff.lint]

# ignore long lines
ignore = ["E501", "E741", "PD011"]

select = [
    # ruff defaults
    "E4",
    "E7",
    "E9",
    "F",
    # ruff defaults
    # TODO deal with docstring issues in a future PR
    #"D100",
    #"D101",
    #"D102",
    #"D103",
    #"D202",
    #"D212",
    #"D413",
    #"D415",
    #"D417",
    "NPY",
    "PD",
]
