# Design philosophy


## {{< fa brands python >}} Familiar

tsod aims to use a syntax familiar to users of scientific computing libraries such as Pandas & sckit-learn.

## {{< fa download >}} Easy to install

```bash
$ pip install tsod
```


## {{< fa brands osi >}} Open Source​
tsod is an open source project licensed under the MIT license.
The software is provided free of charge with the source code available for inspection and modification.

Contributions are welcome!

## {{< fa comments >}} Easy to collaborate
By developing tsod on GitHub along with a completely open discussion, we believe that the collaboration between developers and end-users results in a useful library.

## {{< fa list-ol >}} Reproducible
By providing the historical versions of tsod on PyPI it is possible to reproduce the behaviour of an older existing system, based on an older version.

**Install specific version**

```bash
pip install tsod==0.2.0
```

## {{< fa brands github >}} Easy access to new features
Features are being added all the time, by developers at DHI in offices all around the globe as well as external contributors using tsod in their work.
These new features are always available from the [main branch on GitHub](https://github.com/DHI/tsod) and thanks to automated testing, it is always possible to verify that the tests passes before downloading a new development version.

**Install development version**

```bash
$ pip install https://github.com/DHI/tsod/archive/main.zip
```