project:
  type: website

website:
  title: ""
  page-footer: "© 2025 DHI Group"
  repo-url: https://github.com/DHI/tsod
  repo-actions: [edit]
  repo-subdir: docs
  page-navigation: true
  
  navbar:
    logo: https://raw.githubusercontent.com/DHI/tsod/main/images/logo/tsod.png
    tools:
    - icon: github
      menu:
      - text: Source Code
        url:  https://github.com/DHI/tsod
      - text: Report a Bug
        url:  https://github.com/DHI/tsod/issues
    left:
      - text: Home
        href: index.qmd
      - text: User Guide
        href: user-guide/getting-started.qmd
      - text: Examples
        href: examples/index.qmd
      - text: API Reference
        href: api/index.qmd    

  sidebar:
    - title: "User Guide"
      style: docked
      contents:
        - user-guide/getting-started.qmd
        - user-guide/design.qmd
    - title: "Examples"
      style: docked
      contents:
        - href: examples/index.qmd
        - href: examples/getting-started.qmd
        - href: examples/detect-on-dataframes.qmd
        - href: examples/example-water-level.qmd

filters:
  - interlinks
interlinks:
  sources:
      pandas: 
        url: https://pandas.pydata.org/docs/

quartodoc:
  options:
    include_inherited: true
  style: pkgdown
  title: API Reference
  dir: api
  package: tsod
  
  renderer:
    style: markdown
    display_name: relative
    

  sections:
    - title: tsod
      desc: ""
      
      contents:
      - RangeDetector
      - ConstantValueDetector
      - ConstantGradientDetector
      - GradientDetector
      - DiffDetector
      - RollingStandardDeviationDetector
      - CombinedDetector
      - HampelDetector
      - load
    
format:
  html:
    theme: cosmo
    css: style.css
    toc: true
