# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Full test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.13"]

    steps:
    - uses: actions/checkout@v3
    - uses: chartboost/ruff-action@v1 # Fail fast if there are any linting errors
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel pytest pytest-cov
    
    - name: Install tsod
      run: |
        pip install .[test]
    - name: Test with pytest
      run: |
        pytest --cov=tsod tests
